# Generated by Django 6.1.1 on 2026-09-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_priority_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ('id',), 'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
        migrations.RemoveField(
            model_name='priority',
            name='created',
        ),
    ]
